### ISSUE TITLE
Graph not showing

### ISSUE THREAD

**Issue by saa938** [acmerobotics/ftc-dashboard#113]
I followed all the steps and I'm trying to tune Feedforward, but the graph isn't showing. It's showing for the Localization test and all the other tests but not for this. 
<img width="1034" alt="Screen Shot 2022-11-27 at 5 54 12 PM" src="https://user-images.githubusercontent.com/83087832/204175479-61a9409a-ec3f-4fa0-8a9f-153b5c6e5332.png">

**Comment by rbrott** [comment]
I'm not sure what the screenshot is supposed to show. Telemetry items will only be available when they are sent and that only happens after init in most op modes.
