### ISSUE TITLE
[Bug] MultipleTelemetry.setAutoClear raises UnsupportedOperationException

### ISSUE THREAD

**Issue by nash-pillai** [acmerobotics/ftc-dashboard#126]
The following code makes me think that this is supposed to be a supported operation:
![image](https://user-images.githubusercontent.com/47931961/213081266-4e787aed-c48d-4e85-98bc-0abd9dd43b29.png)
The opmode crashes when I call this method on MultipleTelemetry but not when I call it on the normal telemetry object.

**Comment by rbrott** [comment]
Thanks for the report. Indeed [`setAutoClear()`](https://github.com/acmerobotics/ftc-dashboard/blob/8ac8b29257dede5f4a13c440fe6756efc270cbb8/FtcDashboard/src/main/java/com/acmerobotics/dashboard/FtcDashboard.java#L350-L352) is an unsupported operation on `TelemetryAdapter`. I intentionally don't support auto clear to allow multiple telemetry packets to be sent in the same "loop" and not have them clear each other, and the current code reflects that reality while (nominally) conforming to the `Telemetry` interface. Granted, I may have misunderstood the semantics here.
