### ISSUE TITLE
Please release 0.3.5 to catch up to SDK 5.3

### ISSUE THREAD

**Issue by alan412** [acmerobotics/ftc-dashboard#13]
There is code in master to catch up to SDK 5.3, but the release hasn't been updated.

**Comment by rbrott** [comment]
Have you encountered a specific issue? Sometimes old releases work with new SDK versions if there were no bytecode changes at the module boundaries.

**Comment by alan412** [comment]
not yet.   But I don't want to find it during competition. :-o

**Comment by rbrott** [comment]
Well you have your wish. 0.3.5 happens to be built with 5.3.
