### ISSUE TITLE
RC app crashes with java.net.SocketException: Socket closed

### ISSUE THREAD

**Issue by MafteiAlbert-Alexandru** [acmerobotics/ftc-dashboard#136]
![Error on DS](https://media.discordapp.net/attachments/1089052131480318005/1089052132033957938/20230325_000213.jpg)
*Credit to Krish|18270 on FTC Discord for the photo*

We've noticed this error occurs when the computer connected to dashboard suddenly disconnects from the RC and the camera stream is active. 

The exception should ideally not crash the RC app.

**Comment by rbrott** [comment]
Which version are you on? The latest version (0.4.9) aims to resolve some of these problems.

**Comment by MafteiAlbert-Alexandru** [comment]
I have to test again, until then I will close the issue.
