### ISSUE TITLE
[Feature] VisionPortal compatibility

### ISSUE THREAD

**Issue by AlphaRant9** [acmerobotics/ftc-dashboard#140]
Hey there! Is there any plans in the future to make a VisionPortal or AprilTagProcessor object compatible with FtcDashboard.getInstance().startCameraStream()?

**Comment by wangxdflight** [comment]
Having the same need. It would be nice to add the support.

**Comment by rbrott** [comment]
I added a new example that hopefully helps: https://github.com/acmerobotics/ftc-dashboard/blob/master/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VisionPortalStreamingOpMode.java. 

You can also use this with `CameraStreamServer`. Not sure why the stock vision portal doesn't implement `CameraStreamSource`.
