### ISSUE TITLE
Graph not showing

### ISSUE THREAD

**Issue by PurplePizza123** [acmerobotics/ftc-dashboard#142]
The graph is not showing while I am on the manual feedforward tuner. I went to the link to the FTC Dashboard. Next I went to ManualFeedforwardTuner Op Mode. Finally I started it and graphed the V0 and VRef. Finally I pressed the graph button in the top right and it did not graph anything.

![Screenshot (2)](https://github.com/acmerobotics/ftc-dashboard/assets/145866753/2772f460-2465-4935-9081-003db6d2bbaa)
![Screenshot (3)](https://github.com/acmerobotics/ftc-dashboard/assets/145866753/23999534-db15-49c7-bd70-0f09d489633c)

**Comment by Devildogs11206** [comment]
I have tried using 2 different laptops.

**Comment by PurplePizza123** [comment]
I had to use microsoft edge instead of google chrome.

**Comment by qwertychouskie** [comment]
Chrome and Edge use the same engine (Chromium), so they should work the same.  Can you post the versions of Chrome and Edge, and whether you have any extensions installed?

**Comment by Devildogs11206** [comment]
> Chrome and Edge use the same engine (Chromium), so they should work the same. Can you post the versions of Chrome and Edge, and whether you have any extensions installed?

Chrome version 117.0.5938.92 
Edge version 117.0.2045.47

**Comment by PurplePizza123** [comment]
> Chrome and Edge use the same engine (Chromium), so they should work the same. Can you post the versions of Chrome and Edge, and whether you have any extensions installed?

I used 
Chrome version 117.0.5938.92
Edge version 117.0.2045.47
And no extensions
