### ISSUE TITLE
Error in FtcDashboard.java

### ISSUE THREAD

**Issue by 23476-OWL-Robotics** [acmerobotics/ftc-dashboard#160]
![image_2024-12-06_113400990](https://github.com/user-attachments/assets/63f05940-56d4-4713-807b-2482b7f1e6a7)
I was looking through RoadRunner / DashBoard files when I noticed an error in FtcDashboard,java. Everything is up to date and it does not throw any errors when running gradle.

**Comment by rbrott** [comment]
If there aren't errors when building with Gradle, it's an IDE / Android Studio problem.
