### ISSUE TITLE
Pause graph?

### ISSUE THREAD

**Issue by jasonsue53** [acmerobotics/ftc-dashboard#17]
Is there any way to pause or rewind the graph?  To this point I haven't been able to get much value out of the graph component of the dashboard because it scrolls out of view so quickly.

**Comment by rbrott** [comment]
Yes, you can pause the graph by pressing space (and resume it by pressing space again). You can also temporally extend it by increasing the window size and physically extend it by using the "Original" layout preset.

**Comment by jasonsue53** [comment]
Wonderful.  Thank you Ryan to you and your team for creating and sharing these awesome tools with the community!
