### ISSUE TITLE
Config only works with text input boxes

### ISSUE THREAD

**Issue by AdrianVovk** [acmerobotics/ftc-dashboard#3]
I'm having trouble using other types of config options. For Enums and Booleans, the option will be marked modified, but will not actually update. Pressing the save icon (to apply the modification) will just reset the option to what it was previously (the default). In other words, it is impossible to change these options. I suspect this is a frontend issue

**Comment by rbrott** [comment]
Should be fixed now. I'll prepare a new release soon.

**Comment by AdrianVovk** [comment]
Not sure if you intentionally left the change in, but it seems that you changed the IP address of the dashboard in `dash/config.json`.

**Comment by rbrott** [comment]
Oops 🤦‍♂️

**Comment by rbrott** [comment]
Yeah I just patched the previous release.
