### ISSUE TITLE
Stream camera view not with vuforia

### ISSUE THREAD

**Issue by adamrubinfeld** [acmerobotics/ftc-dashboard#30]
Hi
I mentor team and contently we work on vision recognition and we need to test the pipeline and that very hard the see the camera view from robot control that any way we can send the camera view to the dashboard (we using easyOpenCV)

**Comment by rbrott** [comment]
Yes, you can pass an instance of EOCV `OpenCvCamera` to dash `FtcDashboard#startCameraStream()`.

**Comment by adamrubinfeld** [comment]
Can you send me example?

**Comment by rbrott** [comment]
Take any EOCV example and just add `FtcDashboard.getInstance().startCameraStream(...);` with the appropriate arguments. For instance, take [this example](https://github.com/OpenFTC/EasyOpenCV/blob/master/examples/src/main/java/org/openftc/easyopencv/examples/InternalCamera1Example.java) and add `FtcDashboard.getInstance().startCameraStream(phoneCam, 0)` on line 98.

**Comment by adamrubinfeld** [comment]
I will try tomorrow
I tried that before 4 days and that does a error of network or something

**Comment by FROGbots-4634** [comment]
> I tried that before 4 days and that does a error of network or something

So..... yeah... about that.... due to an oversight on my part, the internal camera v1 implementation actually runs on the UI thread, and Android will crash your app on purpose if you do network on the UI thread. Try switching to the EOCV camera v2 implementation.

**Comment by adamrubinfeld** [comment]
@FROGbots-4634 And if I working with webcam?

**Comment by FROGbots-4634** [comment]
@adamrubinfeld webcams should not pose an issue.

**Comment by adamrubinfeld** [comment]
Ok tnx
I will try tomorrow and give answer of that work

**Comment by adamrubinfeld** [comment]
Work 
Tank you very much guys
