### ISSUE TITLE
NaN values

### ISSUE THREAD

**Issue by smartynenko** [acmerobotics/ftc-dashboard#32]
Dashboard appear not being able to handle NaN values. When NaN values is sent as value in Telemetry packet is kills the dashboard - starting stopping op modes and controllers still work, but field, graph and telemetry stop working.

**Comment by NoahBres** [comment]
I can't recreate this issue.

https://user-images.githubusercontent.com/6739076/103120663-63ba4300-463e-11eb-87f8-3c11b6d43735.mp4

You can see that NaN is sent in a loop in the telemetry packet (on the right on line 79) and the field, config, and graph work fine.
