### ISSUE TITLE
Make the graphing button more obvious

### ISSUE THREAD

**Issue by NoahBres** [acmerobotics/ftc-dashboard#33]
People seem to be really confused by the show graph button. They do not recognize that the icon is a button. Perhaps add some text (despite possibly making it ugly) to make the purpose clear. Or some border.

**Comment by henopied** [comment]
I agree that making the fact that the icon acts as a button more apparent would be good. Additionally it might help to pull in this [icon](https://materialdesignicons.com/icon/chart-line) from Material Design Icons (a community icon.)

**Comment by NoahBres** [comment]
Fixed in PR #37
