### ISSUE TITLE
Disable Dashboard should be accessible from DS

### ISSUE THREAD

**Issue by dgorbunov** [acmerobotics/ftc-dashboard#43]
With the onset of Control Hubs, it is important to be able to disable the dashboard from the Driver Station phone.

**Comment by TimVargo** [comment]
I was going to make a very similar comment.  Problem is that the DS code is not open source like the RC code is, so how could this be accomplished?  Perhaps a disable command could be built into the RC web interface, and/or an API call?

**Comment by rbrott** [comment]
I see two easy options:
* Expose `FtcDashboard#enable()`/`FtcDashboard#disable()` (with changes to modify shared preferences) and let users incorporate them into their own op modes.
* Add instance op mode registrar that registers enable/disable op modes with `FtcDashboard#registerOpModes()`. 

I think I prefer the latter.

I guess disabling from the UI is convenient, but the enable/disable asymmetry bothers me.

**Comment by dgorbunov** [comment]
Thanks for adding this. This could just be me, but upon bumping the version to 0.40 in build.gradle and syncing, it seems FtcDashboard.java isn't updated to include the new op mode registering. Is there something I'm doing wrong? I've tried invaliding gradle cache and deleting all of it.

**Comment by rbrott** [comment]
I intend for registration to happen automatically without any changes. To suppress it, pass `true` to `FtcDashboard.start()`.

**Comment by dgorbunov** [comment]
That method is not present in FtcDashboard for me, just start().

**Comment by dgorbunov** [comment]
For some reason 0.3.10 is only visible to FtcRobotControllerActivity but in other classes I can access version 0.4.0

**Comment by rbrott** [comment]
Ah you will have to update the version in both Gradle files.

**Comment by dgorbunov** [comment]
Ah, totally missed that. Thanks!

**Comment by TimVargo** [comment]
Nicely done!
