### ISSUE TITLE
sdk5.0 setup

### ISSUE THREAD

**Issue by David10238** [acmerobotics/ftc-dashboard#5]
when I try setting up Dashboard v3.0.0 with sdk v5.0 FtcDashboard.attachWebServer(service.getWebServer()); throws a compiler error.
attachWebServer(org.firstinspires.ftc.robotcore.internal.webserver.WebServer) in FtcDashboard cannot be applied to (com.qualcomm.robotcore.util.WebServer)

**Comment by rbrott** [comment]
Yup. v5.0 introduced breaking changes to the web server API (there's even a new module!). It'll be fixed in the next release.
