### ISSUE TITLE
Dashboard doesn't save config values

### ISSUE THREAD

**Issue by odpgit** [acmerobotics/ftc-dashboard#51]
We are running the latest version of Road Runner Quickstart (just pulled 15 minutes ago), and the dashboard allows new values to be entered into the config value fields, but pressing the save icon does not actually save them. They stay marked with an asterisk. We had this problem a week or two ago on an earlier version, so it's probably not related to tonight's pull.

Any ideas?

**Comment by rbrott** [comment]
I haven't been able to test, but I'm pretty sure this is the culprit: https://github.com/acmerobotics/ftc-dashboard/blob/7f42501c2f234221fe4cbfd9a41bda12a66d2cac/FtcDashboard/dash/src/containers/ConfigView.tsx#L50

For now, you can downgrade to 0.3.10 or save variables individually.
