### ISSUE TITLE
Dashboard stops working ( WebSocket connection to 'ws://192.168.43.1:8000/' failed)

### ISSUE THREAD

**Issue by EddieDL** [acmerobotics/ftc-dashboard#60]
We have been using FTC-Dashboard for 2 years now without issue. Two days ago it just stopped working and we see the following error in the browser.

`WebSocket connection to 'ws://192.168.43.1:8000/' failed:`

We have tried to investigate the issue, but aren't sure where to look. We have also tried:
- Using versions of our code from before we had this issue
- Reinstalling the Control Hub OS (thinking maybe something was broken on the control hub).

What should we be doing to investigate why things stopped working.

![image](https://user-images.githubusercontent.com/10708940/115155227-f0a16600-a04c-11eb-9133-96333af0b7a1.png)

**Comment by EddieDL** [comment]
@rbrott @NoahBres Do either of you have any idea about why this would be happening?

**Comment by EddieDL** [comment]
We figured this issue out. Apparently someone ran the "Disable Dashboard" command and no one else knew it. Since the web pages seems to be still sent back to the browser. Perhaps it should have a message stating that the dashboard is currently disabled.

Or you can just check for that :) 

Wish someone would have thought of that sooner.

**Comment by NoahBres** [comment]
@rbrott Can you kill the webserver as well when dash is disabled?

**Comment by rbrott** [comment]
Sure, one can register `null` request handlers.

**Comment by EddieDL** [comment]
Killing the webserver would also help, is that something you can do in the installation logic? Ideally just a way to know that it is turned off not "broken".
