### ISSUE TITLE
Render telemetry view via `dangerouslySetInnerHTML`

### ISSUE THREAD

**Issue by NoahBres** [acmerobotics/ftc-dashboard#61]
Telemetry view: render via [dangerously set inner html](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) to enable to enable the fancy HTML Logging from the SDK.

~~Implementation tbd~~

~~Probably requires manual parsing as the tags that the Android textview supports aren't native HTML. Maybe a simple regex replace will suffice.~~

**Comment by NoahAndrews** [comment]
I believe the supported tags should also be valid HTML. It's just that many valid HTML tags don't work in the Android TextView.

**Comment by NoahBres** [comment]
Ah you're right. I was testing the HTML properties (color, font, etc.) on non-`<font>` tags. Wasn't aware that it was limited to that tag. But it seems to work fine. 

So no parsing necessary! A simple PR to just switch to dangerouslySetInnerHTML should work great!

**Comment by NoahBres** [comment]
0.4.5
