### ISSUE TITLE
Document the camera stream method somewhere public

### ISSUE THREAD

**Issue by NoahBres** [acmerobotics/ftc-dashboard#68]
This is asked relatively often in the Discord.

`FtcDashboard.getInstance().startCameraStream(camera, 0);`

**Comment by NoahBres** [comment]
Perhaps state that when using EOCV, it requires the camera 2 api: https://github.com/acmerobotics/ftc-dashboard/issues/30#issuecomment-699568254

**Comment by rbrott** [comment]
The docs link to a sample with that line, although some exposition on `CameraStreamSource` and its implements might be useful.
