### ISSUE TITLE
documentation for teams migrating from 0.4.2

### ISSUE THREAD

**Issue by IronReignRobotics** [acmerobotics/ftc-dashboard#70]
If you used dashboard 0.4.2 or earlier, there were numerous places you had to sprinkle integration code into ftcrobotcontroller.java.

That seems to have been done away with by using annotation hooks, but it took a bit of work to figure that out and remove those bits. Please add some documentation to help previous users migrate.

But we haven't been fully successful. When we go to the dash page we are getting the response:

Mime type unknown: uri='/dash' path='dash'

In case it matters, this is for an OpenRC project

**Comment by rbrott** [comment]
> In case it matters, this is for an OpenRC project

Check that your OpenRC distribution includes the RC web server.

**Comment by IronReignRobotics** [comment]
It does include the web server. I can see the onbot java environment in a
browser when I downgraded dashboard back to 0.4.2, though pulling up
dashboard crashes because of 7.0 sdk version changes.

**Comment by IronReignRobotics** [comment]
Thanks for the help, there were merge errors in update to 7.0. It's working now.
