### ISSUE TITLE
Add environmental variable for web socket ip in the local dev instructions

### ISSUE THREAD

**Issue by NoahBres** [acmerobotics/ftc-dashboard#71]
Add environmental variable for web socket ip in the local dev instructions.

Perhaps also detail a project structure and basic workings overview (how telemetry is ingested from redux into props, etc.) to make contribution a little easier.

**Comment by rbrott** [comment]
> Add environmental variable for web socket ip in the local dev instructions.

I'll add a note. 
 
> Perhaps also detail a project structure and basic workings overview (how telemetry is ingested from redux into props, etc.) to make contribution a little easier.

I'll consider more extensive documentation of internals. With the current number of contributors, I'm happy to give individualized code pointers for specific changes.
