### ISSUE TITLE
mime type unknown uri='/dash' path='dash' while trying to access FTC Dashboard

### ISSUE THREAD

**Issue by anaconda121** [acmerobotics/ftc-dashboard#74]
We're trying to set up FTC dashboard and we keep getting this error:

![image](https://user-images.githubusercontent.com/38384138/146267156-7fb7d702-6298-42da-9ef5-0213cce876a1.png)

we've followed the instructions here: https://acmerobotics.github.io/ftc-dashboard/gettingstarted.

any ideas?

**Comment by rbrott** [comment]
I would check that you've properly incorporated the 7.0 SDK `FtcRobotControllerActivity` changes (see https://github.com/acmerobotics/ftc-dashboard/issues/70#issuecomment-946724882).

**Comment by anaconda121** [comment]
We used the roadrunner quickstart codebase and now everything works! Thank you!!
