### ISSUE TITLE
fails to connect to the dashboard wifi

### ISSUE THREAD

**Issue by subash0793** [acmerobotics/ftc-dashboard#77]
Control hub connects to the IDE, and I can build the program. I can see the dashboard connection running localhost, but it fails to load the other gui, and also no wifi connection shown in the dashboard.

**Comment by rbrott** [comment]
I'm confused about your setup. The standard way to use dash is (1) add dependency, (2) push code, (3) connect to the RC/CH access point, and (4) navigate to the appropriate URL. Does this work for you?

**Comment by subash0793** [comment]
We were able to figure it out. It was problem with the gradle. Gradle were not properly in sync. Once the sdk was reinstalled and gradle was reconfigured it worked.
