### ISSUE TITLE
include dashboard-0.4.4-SNAPSHOT.aar not working

### ISSUE THREAD

**Issue by wangxdflight** [acmerobotics/ftc-dashboard#79]
I am trying to compile my own version of dashboard. Tried "publishToMavenLocal " as instructed in the documentation, it worked well.
Is this the only approach?
I also tried to include dashboard in build.dependencies.gradle as below.  But it doesn't work. 
Disable/enable dashboard is not shown in the menu, and web browser shows "Mime type unknown: uri='/dash' path='dash'". Web server is indeed running though, and the information on "Program&Manage" page looks complete. 

Looks like the local repo folder has several other files as well. Is it possible to make it work without using local repo approach?

    //implementation 'com.acmerobotics.dashboard:dashboard:0.4.4'
    implementation files('../libs/dashboard-0.4.4-SNAPSHOT.aar')

**Comment by rbrott** [comment]
I haven't reproduced the issue, but I suspect you're missing some dependencies specified in the POM. You may need to add [these lines](https://github.com/acmerobotics/ftc-dashboard/blob/c27aeb71772b7a4f6400d8704da4d1d8d2fdb907/FtcDashboard/build.gradle#L98-L102).

**Comment by wangxdflight** [comment]
Great...it works after adding these lines....It was weird it didn't complain in build process.

Appreciate your prompt help!
