### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by nash-pillai** [acmerobotics/ftc-dashboard#82]
I would like to add features to FTC Dash and share them with the community. However, since there isn't a license, I do not know what rights I have or what restrictions exist regarding my use of the code.

When you do not include a license, the law assumes that you retain all rights to the code, and people who make modifications to or redistribute the code are in violation of the law. I'd recommend the GPLv3 license since it requires people who improve the code to share their improvements with the community. If you do not want this requirement, the MIT license is another good choice.

[Disclaimer: I am not a lawyer and the previous statements may be inaccurate]

**Comment by qwertychouskie** [comment]
Probably easiest to just carry the license over from the SDK itself (https://github.com/FIRST-Tech-Challenge/FtcRobotController/blob/master/LICENSE).
