### ISSUE TITLE
Stream camera view not working with tensorflow

### ISSUE THREAD

**Issue by wangxdflight** [acmerobotics/ftc-dashboard#99]
I am able to get camera view for opencv (apriltag) and vuforia, but not with tensor flow.
Is it supposed to work?

Thanks a lot!

**Comment by rbrott** [comment]
It should work. To debug, you can try setting a breakpoint in `TFObjectDetectorImpl#accept()` and seeing if it gets called. You can also try using the DS camera stream preview which relies on many of the same code paths.

**Comment by wangxdflight** [comment]
Thanks for your reply. It now works. But I had to do code change as below in ConceptTensorFlowObjectDetection.java:
         /*
          * Configure Vuforia by creating a Parameter object, and passing it to the Vuforia engine.
          */
-        VuforiaLocalizer.Parameters parameters = new VuforiaLocalizer.Parameters();
+        int cameraMonitorViewId = hardwareMap.appContext.getResources().getIdentifier("cameraMonitorViewId", "id", hardwareMap.appContext.getPackageName());
+
+        VuforiaLocalizer.Parameters parameters = new VuforiaLocalizer.Parameters(cameraMonitorViewId);

**Comment by wangxdflight** [comment]
But the camera view in dashboard still doesn't show the detection bounding boxes.

**Comment by rbrott** [comment]
If I'm reading the source right, more-or-less the same image is shown on the dashboard as is shown on the RC screen. You're free to write your own `CameraStreamSource` implementation if you want to further manipulate the `Bitmap` that will be sent.

**Comment by wangxdflight** [comment]
It works now...Thanks.
